Client {
  Name = "{{ bareos_client_name }}"
{% if bareos_client_max_jobs is defined and bareos_client_max_jobs %}
  Maximum Concurrent Jobs = {{ bareos_client_max_jobs }}
{% endif %}

  TLS Enable = yes
  TLS Require = yes
{% if bareos_client_heartbeat is defined and bareos_client_heartbeat %}

  Heartbeat Interval = {{ bareos_client_heartbeat }}
{% endif %}

  # remove comment from "Plugin Directory" to load plugins from specified directory.
  # if "Plugin Names" is defined, only the specified plugins will be loaded,
  # otherwise all filedaemon plugins (*-fd.so) from the "Plugin Directory".
  #
  # Plugin Directory = "/usr/lib/bareos/plugins"
  # Plugin Names = ""
}
